### ISSUE TITLE
* kuna-sdk vs ccxt

### ISSUE THREAD

**Issue by olexiyb** [CoinWizard/kuna-sdk#3]
I have discovered library that actually supports Kuna.
https://www.npmjs.com/package/ccxt

Do we want to switch to ccxt inside? Just wanted to get your opinion.

**Comment by m-tymchyk** [comment]
Yes, it's possible.
But I've created this SDK, because `ccxt` less mobile to release a "production ready" changes (like adding new currency or market).

And Kuna announced a brand new API with similar interface as Binance API. This SKD will be first that support new Kuna API.

If we switch to **cctx** inside, that we will became slow as **cctx** :)

**Comment by olexiyb** [comment]
Fare point
